# Generated by Django 3.2.8 on 2021-10-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FindingAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(blank=True, max_length=255)),
                ('reference_code', models.CharField(blank=True, max_length=255)),
                ('name_and_location', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('extent', models.CharField(blank=True, max_length=255)),
                ('creator', models.CharField(blank=True, max_length=255)),
                ('scope_and_content', models.TextField()),
                ('governing_access', models.TextField()),
                ('languages', models.CharField(blank=True, max_length=255)),
                ('rights', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NAFANLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField()),
                ('log_type', models.CharField(choices=[('E', 'Exception'), ('I', 'Info'), ('L', 'Login')], max_length=1)),
                ('log_message', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='NAFANLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='NAFANUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('user_type', models.CharField(blank=True, max_length=32)),
                ('password', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(default='Inactive', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(max_length=255)),
                ('repository_name', models.CharField(max_length=255, verbose_name='Repository')),
                ('name_notes', models.CharField(blank=True, max_length=255)),
                ('parent_organization', models.CharField(blank=True, max_length=255)),
                ('repository_name_authorized', models.CharField(blank=True, max_length=255)),
                ('repository_identifier_authorized', models.CharField(blank=True, max_length=255)),
                ('repository_type', models.CharField(blank=True, max_length=255)),
                ('location_type', models.CharField(blank=True, max_length=255)),
                ('street_address_1', models.CharField(blank=True, max_length=255)),
                ('street_address_2', models.CharField(blank=True, max_length=255)),
                ('po_box', models.CharField(blank=True, max_length=255)),
                ('st_city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('st_zip_code_5_numbers', models.CharField(blank=True, max_length=255)),
                ('st_zip_code_4_following_numbers', models.CharField(blank=True, max_length=255)),
                ('street_address_county', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('latitude', models.CharField(blank=True, max_length=255)),
                ('longitude', models.CharField(blank=True, max_length=255)),
                ('language_of_entry', models.CharField(blank=True, max_length=255)),
                ('date_entry_recorded', models.CharField(blank=True, max_length=255)),
                ('entry_recorded_by', models.CharField(blank=True, max_length=255)),
                ('source_of_repository_data', models.CharField(blank=True, max_length=255)),
                ('url_of_source_of_repository_data', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=5096)),
                ('geocode_confidence', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('repository_name', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Repositories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('repository_name', models.CharField(max_length=255)),
            ],
        ),
    ]
