# Generated by Django 3.2.8 on 2021-10-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0002_auto_20211029_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NAFAN_MARC',
        ),
        migrations.DeleteModel(
            name='PDF',
        ),
        migrations.DeleteModel(
            name='Schema',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
