# Generated by Django 3.2.8 on 2021-11-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0003_auto_20211029_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAFANAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(max_length=254)),
                ('targetID', models.IntegerField()),
                ('target_type', models.CharField(max_length=10)),
                ('audit_action', models.CharField(max_length=10)),
                ('audit_time', models.DateTimeField()),
                ('notes', models.CharField(max_length=2048)),
            ],
        ),
        migrations.AlterField(
            model_name='repository',
            name='repo_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
