# Generated by Django 3.2.8 on 2021-12-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0004_auto_20211116_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
