# Generated by Django 3.2.8 on 2021-12-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0005_repository_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='description',
            field=models.CharField(blank=True, max_length=5096),
        ),
        migrations.AddField(
            model_name='repository',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='repository',
            name='status',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
