# Generated by Django 3.2.8 on 2021-12-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0006_auto_20211209_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
