# Generated by Django 3.2.8 on 2022-03-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0007_alter_repository_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAFANContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='user_repositories',
            name='repository_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
