# Generated by Django 3.2.8 on 2022-03-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0008_auto_20220303_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='elasticsearch_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='findingaid',
            name='date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='findingaid',
            name='governing_access',
            field=models.TextField(blank=True),
        ),
    ]
