# Generated by Django 3.2.8 on 2022-03-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0010_findingaid_elasticsearch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nafanuser',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
