# Generated by Django 3.2.8 on 2022-03-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0013_nafanjoinus'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='governing_access',
            field=models.CharField(blank=True, max_length=5096),
        ),
        migrations.AddField(
            model_name='repository',
            name='harvest_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
