# Generated by Django 3.2.8 on 2022-04-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0015_aidprofile_harvestprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidprofile',
            name='repository_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='aidprofile',
            name='rights',
            field=models.TextField(blank=True),
        ),
    ]
