# Generated by Django 3.2.8 on 2022-04-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0016_auto_20220405_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestprofile',
            name='harvest_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
