# Generated by Django 3.2.8 on 2022-04-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0018_alter_harvestprofile_repository_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='DPLA',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='repository_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
