# Generated by Django 3.2.8 on 2022-05-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0019_auto_20220419_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nafanjoinus',
            name='multiple_organizations',
        ),
        migrations.AddField(
            model_name='nafanjoinus',
            name='message',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
