# Generated by Django 3.2.8 on 2022-05-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0020_auto_20220525_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='repository_link',
        ),
        migrations.AddField(
            model_name='findingaid',
            name='repository_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
