# Generated by Django 3.2.8 on 2022-06-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0022_auto_20220602_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findingaid',
            name='aid_type',
        ),
        migrations.AddField(
            model_name='findingaid',
            name='last_update',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='findingaid',
            name='updated_by',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
