# Generated by Django 3.2.8 on 2022-06-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0023_auto_20220606_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaid',
            name='aid_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
