# Generated by Django 3.2.8 on 2022-06-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0024_findingaid_aid_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findingaid',
            name='name_and_location',
        ),
    ]
