# Generated by Django 3.2.8 on 2022-06-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0025_remove_findingaid_name_and_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaid',
            name='revision_notes',
            field=models.CharField(blank=True, max_length=1023),
        ),
    ]
