# Generated by Django 3.2.8 on 2022-06-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0026_findingaid_revision_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingAidSubjectHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_aid_id', models.CharField(blank=True, max_length=32)),
                ('subject_header', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
