# Generated by Django 3.2.8 on 2022-06-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0027_findingaidsubjectheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaid',
            name='digital_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
