# Generated by Django 3.2.8 on 2022-06-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0028_findingaid_digital_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingAidAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_aid_id', models.CharField(blank=True, max_length=32)),
                ('revision_notes', models.CharField(blank=True, max_length=255)),
                ('update_date', models.DateField(null=True)),
                ('updated_by', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
