# Generated by Django 3.2.8 on 2022-06-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0029_findingaidaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestprofile',
            name='harvest_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
