# Generated by Django 3.2.8 on 2022-06-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0030_harvestprofile_harvest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestprofile',
            name='harvest_day',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='harvestprofile',
            name='harvest_time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
