# Generated by Django 3.2.8 on 2022-06-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0035_findingaid_originals_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaid',
            name='parentID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='findingaid',
            name='progenitorID',
            field=models.IntegerField(default=0),
        ),
    ]
