# Generated by Django 3.2.8 on 2022-06-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0036_auto_20220624_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaid',
            name='scope_and_content_raw',
            field=models.CharField(blank=True, max_length=5255),
        ),
    ]
