# Generated by Django 3.2.8 on 2022-06-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0037_findingaid_scope_and_content_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaid',
            name='component',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
