# Generated by Django 3.2.8 on 2022-07-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0038_findingaid_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingaid',
            name='citation',
            field=models.CharField(blank=True, max_length=1255),
        ),
        migrations.AlterField(
            model_name='findingaid',
            name='creator',
            field=models.CharField(blank=True, max_length=1255),
        ),
        migrations.AlterField(
            model_name='findingaid',
            name='extent',
            field=models.CharField(blank=True, max_length=1255),
        ),
        migrations.AlterField(
            model_name='findingaid',
            name='languages',
            field=models.CharField(blank=True, max_length=1255),
        ),
        migrations.AlterField(
            model_name='findingaid',
            name='rights',
            field=models.CharField(blank=True, max_length=1255),
        ),
    ]
