# Generated by Django 3.2.8 on 2022-07-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0039_auto_20220706_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingaid',
            name='scope_and_content',
            field=models.TextField(blank=True),
        ),
    ]
