# Generated by Django 3.2.8 on 2022-07-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0041_auto_20220706_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaid',
            name='intra_repository',
            field=models.CharField(blank=True, max_length=1255),
        ),
    ]
