# Generated by Django 3.2.8 on 2022-07-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0043_chronolgy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chronolgy',
            new_name='Chronology',
        ),
    ]
