# Generated by Django 3.2.8 on 2022-07-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0044_rename_chronolgy_chronology'),
    ]

    operations = [
        migrations.AddField(
            model_name='chronology',
            name='sort_order',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
