# Generated by Django 3.2.8 on 2022-07-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0046_alter_chronology_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaid',
            name='level',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
