# Generated by Django 3.2.8 on 2022-07-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0047_findingaid_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaid',
            name='acqinfo',
            field=models.CharField(blank=True, max_length=2255),
        ),
        migrations.AddField(
            model_name='findingaid',
            name='custodhist',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='findingaid',
            name='processinfo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
