# Generated by Django 3.2.8 on 2022-07-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0048_auto_20220706_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingaid',
            name='acqinfo',
            field=models.CharField(blank=True, max_length=5255),
        ),
    ]
