# Generated by Django 3.2.8 on 2022-07-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0050_controlaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaid',
            name='container',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
