# Generated by Django 3.2.8 on 2022-07-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAFAN', '0052_auto_20220711_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaid',
            name='note',
            field=models.CharField(blank=True, max_length=555),
        ),
    ]
